
version: '3'

services:
  elixir:
    build:
      context: docker/elixir
    volumes:
      - .:/var/app
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  postgres:
    build:
      context: docker/postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    environment:
      - EDITOR=vim

  node:
    build:
      context: docker/node
    volumes:
      - .:/var/app
    environment:
      - NODE_ENV=development
